apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: rcc
  name: rcc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rcc
    spec:
      containers:
      - image: 172.26.1.182:8082/c2m_sbx:${env.BUILD_NUMBER}
        name: rcc
        ports:
        - name: rcc
          containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: rcc
  labels:
    name: rcc
spec:
  selector:
    name: rcc
  type: NodePort
  ports:
  - nodePort: 32000
    port: 8080
    targetPort: 8080
